language: cpp
dist: bionic
compiler:
  - clang
  - gcc
env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - cmake --build . --target test-small
